import { Injectable } from '@angular/core';
import { of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ProductoServiceService {  
  private banners = {
    'SLEEPING': '../assets/images/sleepingbanner.webp',
    'COOKING': '../assets/images/cookingbanner.webp',
    'LIGHTS': '../assets/images/lightsbanner.webp',
    'STORAGE': '../assets/images/storagebanner.webp',
    'TENTS': '../assets/images/tentsbanner.webp',
    'APPAREL': '../assets/images/apparelbanner.webp',
    'FURNITURE': '../assets/images/furniturebanner.webp'
  };

  private productos = [
    { id: 1, nombre: 'Sleeping Bag & Mat Plus', categoria: 'SLEEPING', descripcion: 'The Sleeping Bag & Mat Plus is a hybrid sleeping bag with an attached sleep mat and retains warmth in temperatures as low as 37.4F. Use the sleeping bag for your outdoor excursions from Spring to Fall. The sleeping bag features a modular dual zipper to separate the top and bottom of the sleeping bag, internal pocket, and attached mat. Pair the Sleeping Bag & Mat Plus with the Stretch Pillow for a full sleeping set-up.', precio: 269.95, imagen: '../assets/images/sleeping1.webp' },
    { id: 2, nombre: 'SS Single', categoria: 'SLEEPING', descripcion: 'The SS Single is a Japanese-designed sleeping bag. Use it for outdoor excursions in the spring and summer. The SS Single is an ultra-soft, cushioned sleeping bag that can be used separately or combined with another to accommodate family camping. The unit can be used as a cushion when packed in the accompanying storage case and features an inner pocket for storing phones or other valuables. Pair the SS Single with the High Tension Cot for comfortable outdoor sleeping.', precio: 64.95, imagen: '../assets/images/sleeping2.webp' },
    { id: 3, nombre: 'Entry Pack SS', categoria: 'SLEEPING', descripcion: 'The Entry Pack SS is a Japanese-designed two-piece sleeping set. Use it for outdoor excursions in the spring and summer. The Entry Pack SS includes two ultra-soft, cushioned sleeping bags that can be used separately or combined to accommodate group camping. Each unit can be used as a cushion when packed in the accompanying storage case and features an inner pocket for storing phones or other valuables. Pair the Entry Pack SS with the Alpha Breeze for group camping.', precio: 114.95, imagen: '../assets/images/sleeping3.webp' },
    { id: 4, nombre: 'Ofuton Sleeping Bag Wide', categoria: 'SLEEPING', descripcion: 'Designed in Japan, the Ofuton Sleeping Bag is made of high-performance ammonophoro fiber insulation that retains warmth in temperatures as low as 41F, while the Deobrain processing ensures fabrics retain antibacterial properties. Use the Ofuton Sleeping Bag for outdoor excursions from spring to fall. The bag features a modular dual zipper to serve as both a sleeping bag and a futon. Pair with the Inflatable Mattress 2.5 for an added layer of comfort or explore the Ofuton Sleeping Bag, Wide LX for warmth in temperatures as low as 37F.', precio: 259.95, imagen: '../assets/images/sleeping4.webp' },
    { id: 5, nombre: 'Ofuton Sleeping Bag Wide LX', categoria: 'SLEEPING', descripcion: 'Designed in Japan, the Ofuton Sleeping Bag Wide LX is made of washable down inner that retains warmth in temperatures as low as 37F, while the Deobrain processing ensures antibacterial properties. Use the Ofuton Sleeping Bag Wide LX for year-round camping. The bag features a modular dual zipper to serve as both a sleeping bag and a futon. Pair with the Inflatable Mattress 2.5 for an added layer of comfort or explore the Ofuton Sleeping Bag, Wide for warmer weather needs.', precio: 279.95, imagen: '../assets/images/sleeping5.webp' },
    { id: 6, nombre: 'IGT Camp Kitchen Starter Set', categoria: 'COOKING', descripcion: 'The IGT Camp Kitchen Starter Set includes components for cooking, prepping, cleaning, and storage. Build upon this foundation with extensions, inserts, storage systems, and more included in the IGT Camp Kitchen Collection.', precio: 712.65, imagen: '../assets/images/cooking1.webp' },
    { id: 7, nombre: 'Takibi Fire & Grill', categoria: 'COOKING', descripcion: 'The Takibi Fire and Grill is made of durable stainless steel and designed in Japan for a lifetime of use. Packable, portable, and modular, use the Takibi Fire and Grill to create a gathering anywhere. To cook with charcoal, add on the Fireplace Coal Bed (L). The Takibi Fire and Grill is the heart of an expansive product collection, including Snow Peak’s FR & Takibi apparel, Fire Tool Set, and Jikaro Firering Table.', precio: 319.95, imagen: '../assets/images/cooking2.webp' },
    { id: 8, nombre: 'Chopping Board Set L', categoria: 'COOKING', descripcion: 'The Cutting Board Set L is a foldable wood cutting board and stainless steel knife. Designed with the outdoor cook in mind, the Cutting Board Set L is ideal for prepping larger meals. The cutting board can be unfolded to safely store the full-sized chef knife. The Cutting Board Set L integrates into the Iron Grill Table system for added functionality.', precio: 64.95, imagen: '../assets/images/cooking3.webp' },
    { id: 9, nombre: 'Titanium Spork', categoria: 'COOKING', descripcion: 'Designed in Japan using a historic manufacturing process, the Titanium Spork has been an icon since its launch. Durable, lightweight, and versatile, use the spork anywhere, whether you’re eating at home or outside. The Titanium Spork is available in blue, purple, and green anodized titanium. Pair the Titanium Spork with a Titanium Trek Bowl or Ti-Double 450 Mug.', precio: 8.95, imagen: '../assets/images/cooking4.webp' },
    { id: 10, nombre: 'Kitchen Scissors Set', categoria: 'COOKING', descripcion: 'The Japanese-designed stainless steel Kitchen Scissors Set is designed and manufactured in Japan. Use in indoor or outdoor kitchens. The set includes a garlic press, bottle opener, meat tenderizer, nut cracker and small paring knife. Pair the Kitchen Scissors Set with the Cutting Board Set L.', precio: 107.95, imagen: '../assets/images/cooking5.webp' },
    { id: 11, nombre: 'Folding Torch', categoria: 'COOKING', descripcion: 'With its compact design and wooden handle, the GigaPower Folding Torch is an essential tool for starting a fire or igniting charcoal. To use, unfold the torch, screw on a canister of iso-butane GigaPower fuel, turn the knob to release gas, and ignite. The torch has a powerful flame that will light even the dampest firewood. The GigaPower Folding Torch is the perfect companion for the Takibi Fire & Grill.', precio: 69.95, imagen: '../assets/images/cooking6.webp' },
    { id: 12, nombre: 'Tableware Set L', categoria: 'COOKING', descripcion: 'Designed in Japan, the Tableware Set Single is made of 0.4mm thick stainless steel to produce lightweight, rust-resistant and durable dishes. Use the set to enjoy meals while camping or at home. Dishes included are the Tableware Plate L, Tableware Dish, Tableware Bowl L, and the Tableware Bowl M. All nest together and are housed in an included mesh bag.', precio: 42.95, imagen: '../assets/images/cooking7.webp' },
    { id: 13, nombre: 'Home & Camp Lantern', categoria: 'LIGHTS', descripcion: 'The Home & Camp Lantern is a rechargeable and portable lamp. The lantern has a USB charging stand, adjustable handle, and dimmable warm light. To use, push the power button once to turn it on and off, and to adjust brightness, hold the power button.', precio: 169.95, imagen: '../assets/images/lights1.webp' },
    { id: 14, nombre: 'Hozuki Lantern', categoria: 'LIGHTS', descripcion: 'Designed and made in Japan, the Hozuki Lantern is a versatile battery-powered light. Use it at your desk or campsite table, or utilize the hanging hook for elevated illumination. The Hozuki Lantern features LED Candle Mode, which interplays with the wind and sound to create a soft flickering glow. Pair the Hozuki Lantern with the Lantern Pile Driver for elevated lighting.', precio: 107.95, imagen: '../assets/images/lights2.webp' },
    { id: 15, nombre: 'Hozuki 2.0 Rechargeable Battery', categoria: 'LIGHTS', descripcion: 'The Hozuki Lantern Rechargeable Battery Pack is a replacement for the three AA battery pack needed for the Hozuki lantern and Spot Hozuki. The battery supports lighting up to 10 Hours with continuous use. To use, place the Hozuki 2.0 Rechargeable Battery into the Hozuki Lantern and charge via USB cord.', precio: 59.95, imagen: '../assets/images/lights3.webp' },
    { id: 16, nombre: 'Celes', categoria: 'LIGHTS', descripcion: 'The Celes is a low-profile, multifunctional LED light. The lower light gently illuminates your gathering space, and the upper light shines on the ceiling, functioning as a large light source that illuminates the entire tent. The light features four brightness modes, an adjustable hanger, and can be mounted to a tripod or connected to Tabletop Architect (TTA) components for additional functionality.', precio: 149.95, imagen: '../assets/images/lights4.webp' },
    { id: 17, nombre: 'Stacking Shelf Container 25', categoria: 'STORAGE', descripcion: 'Designed in Japan, the steel Stacking Shelf Container 25 is a versatile storage option. Keep it at home for convenient storage or use it as a grab-and-go option for your camping gear. The Stacking Shelf Container 25 features bamboo handles for extra style and can also fold open to store bulky items such as firewood or blankets. Stack several containers to form a sturdy and durable shelf. Pair the Stacking Shelf Container 25 with the Stacking Shelf Container 50 for multiple storage solutions.', precio: 139.95, imagen: '../assets/images/storage1.webp' },
    { id: 18, nombre: 'Stacking Shelf Container 50 Set', categoria: 'STORAGE', descripcion: 'The Stacking Shelf Container 50 Set is a versatile storage option that features two Stacking Shelf Container 50. The shelves are made of steel and have bamboo handles for sleekness. Stack the containers to form a sturdy, durable shelf to store items at home and on outdoor adventures.', precio: 305.95, imagen: '../assets/images/storage2.webp' },
    { id: 19, nombre: 'Tarp Pole Carry Case', categoria: 'STORAGE', descripcion: 'The Tarp Pole Carrying Case is a Japanese-designed canvas bag. Use it to store all tarp and shelter poles. The Tarp Pole Carrying Case features a sturdy zipper, handles, and ample space for all your poles. Pair the Tarp Pole Carrying Case with Snow Peak Wing Poles and Tarp Poles.', precio: 64.95, imagen: '../assets/images/storage3.webp' },
    { id: 20, nombre: 'Gear Container', categoria: 'STORAGE', descripcion: 'The sturdy Multi Purpose Carry Case is a Japanese-designed bag. Use the Multi Purpose Carry Case to store the Flat Burner, some briquettes or GigaPower canisters. Featuring a mesh cinch top and sturdy handles, the Multi Purpose Carry Case offers a convenient option for storing camp gear. Pair the Multi Purpose Carry Case with Stoves & Grills for durable storage.', precio: 59.95, imagen: '../assets/images/storage4.webp' },
    { id: 21, nombre: 'Multi Container M', categoria: 'STORAGE', descripcion: 'The Multi Container M is a Japanese-designed canvas case. The medium version is ideal for storing gear and campsite essentials. The Multi Container M features reinforced inserts, function-first canvas, and sturdy handles for easy carrying. Pair the Multi Container M with the Solid Stake #30 and the Steel Head Peg Hammer for camp accessory storage.', precio: 79.95, imagen: '../assets/images/storage5.webp' },
    { id: 22, nombre: 'Bottle Carrier', categoria: 'STORAGE', descripcion: 'A convenient carry solution, the Bottle Carrier is designed to securely hold a bottle and cutlery for hands-free, on-the-go travel. Slide the bottle into the main compartment and secure it with the adjustable buckle clasp. Insert Titanium Chopsticks or other small cutlery into the back pocket and secure the flap.', precio: 18.95, imagen: '../assets/images/storage6.webp' },
    { id: 23, nombre: 'Entry Pack TT', categoria: 'TENTS', descripcion: 'Designed with space for the whole family, the Entry Pack Tent & Tarp is the ideal set for any outdoor adventure. The Entry Pack Tent & Tarp combines the Vault Tent with the Amenity Tarp Hexa for the ultimate car camping set-up. With space for four, the tent and tarp can be used together as a full set or separated for additional modularity. Use the tent for sleeping, and the tarp area for gathering and cooking.', precio: 647.95, imagen: '../assets/images/tents1.webp' },
    { id: 24, nombre: 'Penta Tarp in Ivory', categoria: 'TENTS', descripcion: 'The Penta Tarp in Ivory is a minimalist shelter for one or two campers. The Penta Tarp in Ivory is durable, water-resistant, and compact. Intended for use near the water, it features a unique design that allows a paddle to be used as a pole.  Pair with the Penta Ease 1 in Ivory for complete protection from weather elements and for a dedicated sleeping space.', precio: 149.95, imagen: '../assets/images/tents2.webp' },
    { id: 25, nombre: 'Takibi Tarp Hexa Set M', categoria: 'TENTS', descripcion: 'A US-exclusive, the Takibi Tarp Hexa Set M is designed to create fireside gatherings in every season. The waterproof, UV-blocking Ivory Hexa Tarp features an elegant curved shape. Use the tarp on its own or attach the flame-resistant Takibi Inner Roof constructed of aramid fabric to allow for fires underneath the tarp. Secure with the included 1.5mm Aluminum Wing Poles and store the full set in the ivory-colored carrying case.', precio: 549.95, imagen: '../assets/images/tents3.webp' },
    { id: 26, nombre: 'TaLand Lock', categoria: 'TENTS', descripcion: 'The Japanese-designed Land Lock is a tent and shelter combination for up to four adults. Use it for family or friend group camping trips and never worry about space. The Landlock features a spacious gathering area, a private inner tent for sleeping, and two expandable shade panels for additional living space. The Land Lock also features sealable mesh windows that allow for cross breezes during hot summer nights. Pair the Landlock with the Landlock Inner Mat for a comfortable sleeping set-up.', precio: 1899.95, imagen: '../assets/images/tents4.webp' },
    { id: 27, nombre: 'Hexa Ease 1 in Ivory', categoria: 'TENTS', descripcion: 'The Hexa Ease 1 in Ivory is a tent and tarp combination designed for one person. The Hexa Ease 1 in Ivory is compact and lightweight. It features an extended flysheet that offers additional living space and a multi-entrance inner tent with ample mesh ventilation. Pair with the Gigapower Stove and Ti-Mini Solo for a minimalist solo trip.', precio: 499.95, imagen: '../assets/images/tents5.webp' },
    { id: 28, nombre: 'Living Shell Long Pro. in Ivory', categoria: 'TENTS', descripcion: 'Part of the Snow Peak Ivory Series, Living Shell Long Pro. Ivory is a Japanese-designed modular shelter. Use the eye-catching Living Shell Long during group excursions for a seamless integration of nature and the comforts of home. Prop up the front flap for an extended covered space for cooking or gathering. The Living Shell Long features large mesh windows, tri-ventilation, a UV shield and can integrate with the Dock Dome Series. Pair the Living Shell Long Pro. Ivory with the Dock Dome Pro Ivory.', precio: 1999.95, imagen: '../assets/images/tents6.webp' },
    { id: 29, nombre: 'Land Station L Ivory', categoria: 'TENTS', descripcion: 'Part of the Snow Peak Ivory Series, the Land Station is a dynamic tarp designed to accommodate up to eight people. With a variety of set-up options, the Land Station Ivory is an eye-catching centerpiece in camp, whether for sleeping or gathering. The Land Station Ivory is designed to protect from the elements like wind and rain and is made from a fabric that shelters from the sun, while still letting in light.', precio: 1187.95, imagen: '../assets/images/tents7.webp' },
    { id: 30, nombre: 'Alpha Breeze', categoria: 'TENTS', descripcion: 'Designed specifically for the North American camper, the architecture of the Alpha Breeze is inspired by traditional A-Frames and Adirondack cabins. The tent features convenient entry points on all four sides, offering added ventilation, and color-coordinated pieces for simple set-up. The Alpha Breeze provides ample living space, and the vestibule can be converted into an awning for an extended gathering area. Pair with Entry IGT Table for an elevated set-up.', precio: 499.95, imagen: '../assets/images/tents8.webp' },
    { id: 31, nombre: 'Mens Snow Peak x Danner Light II', categoria: 'APPAREL', descripcion: 'The Snow Peak x Danner Light II is a durable trekking boot with a traditional lace-up design. The Light II, a classic Danner style, features a waterproof GORE-TEX liner, Vibram MEGAGRIP® outsole, and a fire-resistant leather upper, with a Snow Peak logo on the heel and a metal lace guard. Available in EE width.', precio: 450.00, imagen: '../assets/images/apparel1.webp' },
    { id: 32, nombre: 'TDS Niobium Concept 3', categoria: 'APPAREL', descripcion: 'The TDS Niobium Concept 3 is a two-part snow boot. The sole features a wide landing area, arch support from New Balances ROLLBAR technology, and a Vibram outsole for stability and grip. The upper features a two-part construction, including waterproof and breathable eVent material for the shell, and insulated water-repellent PRIMALOFT® for the inner boot. The inner boot can be removed and used as a room shoe, making it easy to stay warm and dry both outside and inside the tent.', precio: 300.00, imagen: '../assets/images/apparel2.webp' },
    { id: 33, nombre: 'Winter Down Haori Jacket', categoria: 'APPAREL', descripcion: 'The Winter Down Haori Jacket is a down-insulated and water-repellent jacket. The jacket features a zippered chest pocket, dual zippered side pockets, and an adjustable belt with a FIDLOCK buckle. The face fabric is made from recycled nylon, and the fill is recycled and DWR-treated down.', precio: 679.95, imagen: '../assets/images/apparel3.webp' },
    { id: 34, nombre: 'Recycled Cotton Pullover Hoodie', categoria: 'APPAREL', descripcion: 'The Recycled Cotton Pullover Hoodie is a casual cotton hoodie. It is made of upcycled cotton that is resistant to pilling. The Recycled Cotton Pullover Hoodie features a hood with drawstrings, long sleeves, and dual waist pockets.', precio: 144.95, imagen: '../assets/images/apparel4.webp' },
    { id: 35, nombre: 'Recycled Cotton 5pkt Denim Regular', categoria: 'APPAREL', descripcion: 'The Recycled Cotton 5pkt Denim Regular is a 12.6oz selvedge denim pant. The fabric is 100% recycled denim, with yarn sourced from Guatemala and woven in Japan. The denim features a button closure, zip fly, five pockets, and a straight leg opening.', precio: 159.95, imagen: '../assets/images/apparel5.webp' },
    { id: 36, nombre: 'Renewed Single Action Low Table', categoria: 'FURNITURE', descripcion: 'Designed in Japan, the Renewed Single Action Table Low features a laminated bamboo top in an updated finish and stable aluminum legs. The low version of the Renewed Single Action Table offers more portability and is easy to take on day trips, picnics, and car camping excursions. The Renewed Single Action Table Low folds into a thin panel for compact carrying and storage.  Pair the Renewed Single Action Low Table with the Low Beach Chair for a complete set-up.', precio: 324.95, imagen: '../assets/images/furniture1.webp' },
    { id: 37, nombre: 'Renewed Take! Bamboo Chair Long', categoria: 'FURNITURE', descripcion: 'The Take! Renewed Bamboo Chair Long features bamboo legs, aluminum supports and a comfortable canvas seat. Simply unfold the chair for a stylish seat at home or outdoors. The long version of the Take! Renewed Bamboo Chair offers full lounge support with its extended backrest. Pair the Take! Renewed Bamboo Chair Long with the Renewed Bamboo My Table for a cohesive look.', precio: 249.95, imagen: '../assets/images/furniture2.webp' },
    { id: 38, nombre: 'Low Beach Chair', categoria: 'FURNITURE', descripcion: 'Designed in Japan, the Low Beach Chair has natural wood armrests and a canvas seat. The chair is stylish enough for the home or patio, but sturdy enough to withstand the rigors of camp. The Low Beach Chair features a high-quality wood armrest and back that is 7 inches taller than the Luxury Low Beach Chair. The Low Beach Chair folds into a compact case for efficient storage.', precio: 169.95, imagen: '../assets/images/furniture3.webp' },
    { id: 39, nombre: 'Renewed Single Action Table Low M', categoria: 'FURNITURE', descripcion: 'Designed in Japan, the Renewed Single Action Table Low Medium features a laminated bamboo top in an updated finish and stable aluminum legs. The low version of the Renewed Single Action Table offers more portability and is easy to take on day trips, picnics, and car camping excursions. Use the table for groups of up to four people. The Renewed Single Action Table Low folds into a thin panel for compact carrying and storage. Pair the Renewed Single Action Table Low M with the Low Beach Chair for a complete set-up.', precio: 215.95, imagen: '../assets/images/furniture4.webp' },
    { id: 40, nombre: 'Red Lounge Set', categoria: 'FURNITURE', descripcion: 'Created as a foundational camping furniture setup for our Signature Series, the Red Lounge Set is exclusively available in the U.S. The set includes two Red Folding Chairs for durable, collapsible seating solutions, and the Renewed Bamboo My Table as a sleek, foldable table. This set is ideal for the campsite, backyard, or tailgate.', precio: 409.85, imagen: '../assets/images/furniture5.webp' },
  ];
  
  constructor() { }

  getCategorias() {
    const categorias = ['SLEEPING', 'COOKING', 'LIGHTS', 'STORAGE', 'FURNITURE', 'TENTS', 'APPAREL'];
    const categoriasConCantidad = categorias.map((categoria) => {
      const cantidad = this.productos.filter((p) => p.categoria === categoria).length;
      return { nombre: categoria, cantidad, imagen: `../../assets/images/${categoria.toLowerCase()}.png` };
    });
    return of(categoriasConCantidad);
  }

  getProductosPorCategoria(categoria: string) {
    const productos = this.productos.filter((p) => p.categoria === categoria);
    return of(productos);
  }

  getProducto(id: number) {
    const producto = this.productos.find((p) => p.id === id);
    return of(producto);
  }

  getProductos() {
    return this.productos;
  }
}
